[SEARCH] fix `html_field_analyzer` case handling
superdesk/superdesk-core pull request #2116
Opened 2021-01-18 19:26 UTC by jerome-poisson

Custom `html_field_analyzer` was not using `lowercase` filter, so case
was kept. As a result, words with uppercase in them could not be found
with the search API.

SDCP-423

2021-01-18 19:34 UTC, jerome-poisson commented
note the ES indexes must be flushed after applying this patch (`python manage.py app:flush_elastic_index --sd`).

2021-01-19 09:03 UTC, petrjasek approved these changes

2021-01-19 09:04 UTC, petrjasek requested changes
actually we should do it also for content api index settings, just a few lines below

2021-01-19 13:26 UTC, petrjasek approved these changes

2021-01-19 14:39 UTC, merged